project:
  type: website
  render: "index.qmd"

website:
  title: "Data Infrastructure Framework Project"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
name: "dif-project"
description: |
  Application to the Novo Nordisk Foundation Data Science Research Infrastructure grant.
output_dir: "docs"
theme: theme.css
repository_url: https://github.com/steno-aarhus/dif-project
creative_commons: CC BY
navbar:
  left:
    - icon: "fas fa-home"
      href: index.html
    - icon: "fas fa-globe"
      href: "https://www.stenoaarhus.dk/research"
    - icon: "fab fa-twitter"
      href: "https://twitter.com/StenoAarhusRes"
  source_url: true
format:
  html:
    theme: cosmo
    css: theme.css
    toc: true
    toc_depth: 2
